"""add review

Revision ID: 254a10c77abe
Revises: 05519dd1543c
Create Date: 2024-06-27 21:24:48.937477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254a10c77abe'
down_revision = '05519dd1543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_item_id_items'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_item_id_items'), type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
